FROM node:18.15-buster
RUN useradd -ms /bin/bash userapp && \
    mkdir -p /app && \
    chown -R userapp /app
WORKDIR /app
USER userapp
COPY  package.json .
RUN npm install
COPY . .
EXPOSE 8080
CMD ["node", "server.js"]
